### ISSUE TITLE
Cloud Function return false CORS Error, original code not working at all, after following the steps

### ISSUE THREAD

**Issue by hunterxxx** [AppGalleryConnect/agc-demos#17]
I have used the code from here:
1. https://github.com/AppGalleryConnect/agc-demos/tree/main/Web/agc-cloudfunction-demo-javascript
2. Enabled Cloud Function from AGC Dashboard
3. Modified agConnectConfig in config.js

However, as seen from the picture, it got CORS error, when I clicked run.

![error](https://user-images.githubusercontent.com/7548302/152886250-ab199656-8356-4f60-b9e3-8f1d69e730a9.PNG)

So I:
1. Added `"proxy": "https://connect-dre.dbankcloud.cn/",` in `package.json`
2. Uploaded to https://grouchy-partner.surge.sh/#/

Still, it does not work!

Is it because problem rom your server?

**Comment by Mayism** [comment]
@hunterxxx Know that your question has been answered, thank you for your attention

**Comment by hunterxxx** [comment]
Could you post the answer here? Thanks.

**Comment by yycccc91** [comment]
Just support CORS policy in Europe
